image: golang:1.17

variables:
  REPO_NAME: dfile-secondary-node


before_script:
  - export GO111MODULE="on" 
  - go mod tidy

stages:
  - test
  - build

testing:
  stage: test
  script:
    - go test -p 1 ./...
    - go build -ldflags "-s -w" -o builds/DeNet-Node-linux-amd64
  artifacts:
    paths:
      - builds/
