version: "3.3"
services:
        dfile-node:
                build: .
                network_mode: host
                restart: always
                volumes:
                        - /root:/root
